Artists module
onionToyBoy/MusicCatalog pull request #1
Opened 2021-06-03 12:59 UTC by onionToyBoy

Code style changes + renamed searchReducer + changed async storate source

2021-06-09 14:15 UTC, AnnZar12 requested changes

2021-06-09 14:15 UTC, AnnZar12 commented on MusicCatalog/index.js
> +import('./ReactotronConfig').then(() => console.log('Reactotron Configured'));
Please, check ESLint. You need empty space before import.  Also, you could install Husky to automatically check this kind of style errors.

2021-06-09 14:15 UTC, AnnZar12 commented on MusicCatalog/src/constants/types.js
> +export const SET_ARTISTS = 'SET_ARTISTS';
Filename `types` is not a suitable name for this. It's better to rename it to `actionsTypes` OR move this file to the `actions` folder.

2021-06-09 14:15 UTC, AnnZar12 commented on MusicCatalog/src/modules/Albums/AlbumsScreen.js
>    const [data, setData] = useState([]);
Note for me: This file will be updated in the scope of the next PR(Albums module).

2021-06-09 14:15 UTC, AnnZar12 commented on MusicCatalog/src/modules/Albums/components/Album.js
> +    width: '100%',
flex: 1

2021-06-09 14:15 UTC, AnnZar12 commented on MusicCatalog/src/modules/Artists/actions/albumRender.js
> +export const albumRender = albums => {
It's better to call this function `setAlbums`. Also, you don't need to create a separate file for each action. You can just create an index.js file in the actions folder and paste all module's actions here.

2021-06-09 14:15 UTC, AnnZar12 commented on MusicCatalog/src/modules/Artists/actions/artistRender.js
> +export const artistRender = artists => {
setArtists

2021-06-09 14:15 UTC, AnnZar12 commented on MusicCatalog/src/modules/Artists/actions/trackRender.js
> +export const trackRender = tracks => {
setTracks

2021-06-09 14:15 UTC, AnnZar12 commented on MusicCatalog/src/modules/Artists/components/AlbumTracks.js
> +    dispatch(getTracks(componentId));
`getTracks` by navigation screen ID value is not a good idea. It's better to pass prop `albumId` to the component.

2021-06-09 14:15 UTC, AnnZar12 commented on MusicCatalog/src/modules/Artists/components/AlbumTracks.js
> +    <Track name={item.trackName} number={item.trackNumber} time={item.trackTimeMillis} />
FYI: You can pass this params as `<Track  {...item} />` or `<Track track={item} />`. The current option is acceptable, but sometimes it's hard to read if you pass a lot of values.

2021-06-09 14:15 UTC, AnnZar12 commented on MusicCatalog/src/modules/Artists/components/ArtistsAlbums.js
> +      collectionPrice={checkPrice(item.collectionPrice)}
It's better to pass the `collectionPrice` value and call `checkPrice` function before the render.

2021-06-09 14:15 UTC, AnnZar12 commented on MusicCatalog/src/modules/Artists/components/ArtistsAlbums.js
> +    dispatch(getAlbums(componentId));
The same comments as for the AlbumTracks screen

2021-06-09 14:15 UTC, AnnZar12 commented on MusicCatalog/src/modules/Artists/components/ArtistsScreen.js
> +              text: name + ' albums',
You can also use template strings  \`${name} albums\`

2021-06-09 14:15 UTC, AnnZar12 commented on MusicCatalog/src/modules/Artists/components/Track.js
> +        <Text style={styles.numbers}>{timeConventer(time)}</Text>
Please, move timeConventer(time) to constants

2021-06-09 14:15 UTC, AnnZar12 commented on MusicCatalog/src/modules/Artists/components/Artist.js
> +const onPressArtist =() => onOpenAlbum(name, id)
Please, check ESLint and code style

2021-06-09 14:15 UTC, AnnZar12 commented on MusicCatalog/src/modules/Artists/reducers/tracks.js
> +  tracks: {},
Please, organize the logic to save trucks for different artists.

2021-06-09 14:15 UTC, AnnZar12 commented on MusicCatalog/src/utils/checkPrice.js
> +export const checkPrice = price => (price>0 ? price + ' $' : 'FREE');
You don't need to create a separate file for each helper. Please, create an index.js file and move all utils functions here.

2021-06-11 11:51 UTC, merged

2021-06-11 17:05 UTC, onionToyBoy commented
Artists module